version: 2
jobs:
  build:
    docker:
      - image: php
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libgmp3-dev
      - run:
          name: Install wgets
          command: apt-get install wget -y
      - run: wget https://phar.phpunit.de/phpunit.phar
      - run:
          name: Run tests
          command: phpunit sampleTest