version: 2
jobs:
  build:
    docker:
      - image: php
    steps:
      - checkout
  test1:
    docker:
      - image: php
    steps:
      - checkout
      - run: apt-get install phpunit -y
      - run: phpunit sampleTest
workflows:
  version: 2
  build_and_test:
    jobs:
      - test1