version: 2
jobs:
  build:
    docker:
      - image: php
    steps:
      - checkout
      - run:
          name: Install wgets
          command: apt-get install wget -y
      - run: wget https://phar.phpunit.de/phpunit.phar && mv phpunit.phar phpunit
      - run:
          name: Run tests
          command: phpunit sampleTest