version: 2
jobs:
  build:
    docker:
      - image: php
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libgmp3-dev
      - run: apt-get install php-pear -y
      - run: pear channel-update pear.php.net
      - run: pear upgrade pear
      - run: pear config-set auto_discover 1
      - run: pear install pear.phpunit.de/PHPUnit-3.7.32
      - run:
          name: Run tests
          command: phpunit sampleTest