version: 2
jobs:
  build:
    docker:
      - image: php
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libgmp3-dev
      - run: wget https://phar.phpunit.de/phpunit.phar && mv phpunit.phar phpunit
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: phpunit sampleTest